spring:
  datasource:
    url: jdbc:mysql://${prodDbIp}:3306/ghaSample_prod?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${prodDbId}
    password: ${prodDbPw}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
    com.ll.exam.ghasample.app: info
    org.hibernate.type.descriptor.sql: info
custom:
  site:
    baseUrl: "https://site-a.com"